# Generated by Django 4.2.7 on 2024-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='qty_alert_level',
            field=models.FloatField(default=0),
        ),
    ]
